systemLog:
  destination: file
  path: /Users/admin/tuneablelocal/development/tuneable-backend/logs/mongo.log
  logAppend: true
storage:
  dbPath: /Users/admin/tuneablelocal/development/tuneable-backend/data/db
net:
  bindIp: 127.0.0.1, ::1
  ipv6: true


