# XcodeGen spec for Tuneable iOS app
# Generate project: xcodegen generate (from tuneable-ios directory)
name: Tuneable
options:
  bundleIdPrefix: stream.tuneable
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top
  tabWidth: 4
settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ""
packages: {}
targets:
  Tuneable:
    type: application
    platform: iOS
    sources:
      - path: Tuneable
        name: Tuneable
        excludes:
          - "*.plist"
    settings:
      base:
        INFOPLIST_FILE: Tuneable/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: YES
        PRODUCT_BUNDLE_IDENTIFIER: stream.tuneable.app
        SWIFT_EMIT_LOC_STRINGS: YES
    dependencies: []
schemes:
  Tuneable:
    build:
      targets:
        Tuneable: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
